In [6]:
import numpy as np

In [7]:
def discrete_laplacian_2d(u, dx=1.0, dy=1.0):
    """
    Дискретный оператор Лапласа для 2D сетки
    """
    laplacian = np.zeros_like(u)

    # Центральные разности второго порядка
    for i in range(1, u.shape[0]-1):
        for j in range(1, u.shape[1]-1):
            d2u_dx2 = (u[i+1, j] - 2*u[i, j] + u[i-1, j]) / dx**2
            d2u_dy2 = (u[i, j+1] - 2*u[i, j] + u[i, j-1]) / dy**2
            laplacian[i, j] = d2u_dx2 + d2u_dy2

    return laplacian

# Векторизованная версия (быстрее)
def vectorized_laplacian_2d(u, dx=1.0, dy=1.0):
    """
    Векторизованный оператор Лапласа для 2D сетки
    """
    laplacian = np.zeros_like(u)
    laplacian[1:-1, 1:-1] = (
        (u[2:, 1:-1] - 2*u[1:-1, 1:-1] + u[:-2, 1:-1]) / dx**2 +
        (u[1:-1, 2:] - 2*u[1:-1, 1:-1] + u[1:-1, :-2]) / dy**2
    )
    return laplacian

# Пример использования
x = np.linspace(-2, 2, 10)
y = np.linspace(-2, 2, 10)
X, Y = np.meshgrid(x, y)
U = X**2 + Y**2

laplacian_U = vectorized_laplacian_2d(U, dx=x[1]-x[0], dy=y[1]-y[0])
print("Оператор Лапласа для f(x,y) = x² + y²:")
print(laplacian_U)

Оператор Лапласа для f(x,y) = x² + y²:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 4. 4. 4. 4. 4. 4. 4. 4. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
